incomes/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.incomes_view, name='incomes'),
    path('incomes-table', views.incomes_table, name='incomes-table'),
    path('add-income', views.add_income, name='add-income'),
    path('update-income/<str:pk>', views.update_income, name='update-income'),
    path('delete-income/<str:pk>', views.delete_income, name='delete-income'),
    path('income-chart', views.income_chart, name='income-chart'),
]

kashkoo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('incomes.urls'))
]

incomes/models.py
from django.db import models

# Create your models here.

class Income(models.Model):
    description = models.CharField(max_length=500)
    annual_amount = models.FloatField()
    start_age = models.IntegerField(null=True, blank=True)
    end_age = models.IntegerField(null=True, blank=True)
    growth =  models.FloatField(null=True, blank=True, default=0.0)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-id',)

    

incomes/forms.py
from django import forms
from .models import Income

class IncomeForm(forms.ModelForm):

    class Meta:
        model = Income
        fields = '__all__'



    def clean(self):
        cleaned_data = super().clean()
        st = cleaned_data['start_age']
        end = cleaned_data['end_age']
        growth = cleaned_data['growth']
        if not st and not end:
            raise forms.ValidationError({
                'start_age':'Please select either a starting or ending age.',
                'end_age':'Please select either a starting or ending age.',
                })

        if st != None and end != None and st > end :
            raise forms.ValidationError({
                'start_age':'The start age must be less than the end age.',
                'end_age':'The start age must be less than the end age.'
                })
        if st == 65 and growth:
            raise forms.ValidationError({
                'growth':'The start age must be less than 65 for you to add growth',
                })

        return cleaned_data

incomes/views.py
import json

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from .forms import IncomeForm
from .models import Income


def incomes_view(request):
    return render(request, 'incomes/incomes.html')

def incomes_table(request):
    incomes = Income.objects.all()

    return render(request, 'incomes/incomes-table.html', {'incomes':incomes})


def add_income(request):
    if request.method == 'POST':
        form = IncomeForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse(status=204, headers={
                'HX-Trigger': json.dumps({
                'incomesListChanged': None,
                'showSuccessMessage': 'Income added successfully'
                })
            })
    else:
        form = IncomeForm()
        

    return render(request, 'incomes/income-form.html', {'form':form})

def update_income(request, pk):
    income = get_object_or_404(Income, pk=pk)
    form = IncomeForm(instance=income)
    if request.method == 'POST':
        form = IncomeForm(request.POST, instance=income)
        if form.is_valid():
            form.save()
            return HttpResponse(status=204, headers={
                'HX-Trigger': json.dumps({
                'incomesListChanged': None,
                'showSuccessMessage': 'Income updated successfully'
                })
            })

    return render(request, 'incomes/income-form.html', {'form':form})

def delete_income(request, pk):
    income = get_object_or_404(Income, pk=pk)
    income.delete()
    return HttpResponse(status=204, headers={
                'HX-Trigger': json.dumps({
                'incomesListChanged': None,
                'showSuccessMessage': 'Income deleted successfully'
                })
            })
def get_growth_rate(a, p, t):
    """
    uses simple interest formula to calculate the rate of growth
    given the annual amount, expected amount after 65 years and
    the number of years
    """
    # simple interest formula --> A = P(1 + rt)

    
    r = (a - p) / (p*t)

    return r

def get_single_income_chart_values(pk):
    """
    This function returns a list of the y values 
    for the total income chart
    """
    single_income_values = []

    year = 1 # current income year
    growth_multiplyer = 1 # annual multiplyer factor for incomes with growth
    
    income = Income.objects.get(pk=pk)
    if income.growth:
        rate = get_growth_rate(income.growth, income.annual_amount, 65 - (income.start_age or 40))
    for i in range(40, 101): # selected range is because age is assumed from 40 to 100
        if i <= (income.end_age or 100) and i >= (income.start_age or 40):
            # append the income amount only if age iteration is between
            # the start and end age
            single_income_values.append(int(income.annual_amount * growth_multiplyer)) 

            if income.growth:
                # set the multiplyer factor given the current income year and growth rate
                growth_multiplyer = (1 + (rate * year))
        else:
            single_income_values.append(0)
        year = year + 1
    

    # return a sum of all the single income lists to get a total income list
    return single_income_values

def get_total_income_chart_values():
    """
    This function returns a list of the y values 
    for the total income chart
    """
    single_income_values = []
    total_income_values = []

    year = 1 # current income year
    growth_multiplyer = 1 # annual multiplyer factor for incomes with growth
    
    for income in Income.objects.all():
        if income.growth:
            rate = get_growth_rate(income.growth or 0, income.annual_amount, 65 - (income.start_age or 40))
        for i in range(40, 101): # selected range is because age is assumed from 40 to 100
            if i <= (income.end_age or 100) and i >= (income.start_age or 40):
                # append the income amount only if age iteration is between
                # the start and end age
                single_income_values.append(int(income.annual_amount * growth_multiplyer)) 

                if income.growth:
                    # set the multiplyer factor given the current income year and growth rate
                    growth_multiplyer = (1 + (rate * year))
            else:
                single_income_values.append(0)
            year = year + 1
        # siv meanse single_income_values [[siv1, siv2, ... sivn]] 
        total_income_values.append(single_income_values)

        single_income_values = []
        year = 1
        growth_multiplyer = 1

    # return a sum of all the single income lists to get a total income list
    return [sum(x) for x in zip(*total_income_values)] 

def income_chart(request):
    pk = request.GET.get('pk')
    title = request.GET.get('title')
    if pk:
        y_values = get_single_income_chart_values(pk)
    else:
        y_values = get_total_income_chart_values()

    context = {
        'title':title,
        'y_values':y_values
    }
    return render(request, 'incomes/income-chart.html', context)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html dir="ltr" lang="en">
   <head>
      <meta charset="utf-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <!-- Tell the browser to be responsive to screen width -->
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="" />
      <meta name="author" content="" />
      <!-- Favicon icon -->
      <title>{% block title %}Default Value{% endblock title %}</title>
      <script src="{% static 'dashboard/js/jquery.min.js' %}"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <!-- Custom CSS -->
      <link href="{% static 'dashboard/css/style.min.css' %}" rel="stylesheet" />
      <link href="{% static 'dashboard/css/custom.css' %}" rel="stylesheet" />
      <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/multicheck.css' %}">
      <link href="{% static 'dashboard/css/dataTables.bootstrap.min.css' %}" rel="stylesheet" media="all">
      <link href="{% static 'dashboard/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
      <link href="{% static 'dashboard/css/toastr.min.css' %}" rel="stylesheet">
      <script src="{% static 'dashboard/js/toastr.min.js' %}" type="text/javascript"></script>
      {% block sitecss %}
      {% endblock sitecss %}
   </head>
   <body>
      <!-- ============================================================== -->
      <!-- Preloader - style you can find in spinners.css -->
      <!-- ============================================================== -->
      <div class="preloader">
         <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
         </div>
      </div>
      {% include 'partials/messages.html' %}
      <!-- ============================================================== -->
      <!-- Container fluid  -->
      <!-- ============================================================== -->
      <div class="container-fluid m-20">
         <!-- ============================================================== -->
         <!-- Start Page Content -->
         <!-- ============================================================== -->
         {% block content %}
         {% endblock content %}
         <!-- ============================================================== -->
         <!-- End Page Content -->
         <!-- ============================================================== -->
      </div>
      <!-- ============================================================== -->
      <!-- End container fluid  -->
      <!-- ============================================================== -->
      <!-- Bootstrap tether Core JavaScript -->
      <script src="{% static 'dashboard/js/popper.min.js' %}"></script>
      <script src="{% static 'dashboard/js/bootstrap.min.js' %}"></script>
      <script src="{% static 'dashboard/js/perfect-scrollbar.jquery.min.js' %}"></script>
      <script src="{% static 'dashboard/js/sparkline.js' %}"></script>
      <!--Wave Effects -->
      <script src="{% static 'dashboard/js/waves.js' %}"></script>
      <!--Menu sidebar -->
      <script src="{% static 'dashboard/js/sidebarmenu.js' %}"></script>
      <!--Custom JavaScript -->
      <script src="{% static 'dashboard/js/custom.min.js' %}"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
      <script src="https://unpkg.com/htmx.org@1.7.0" integrity="sha384-EzBXYPt0/T6gxNp0nuPtLkmRpmDBbjg6WmCUZRLXBBwYYmwAUxzlSGej0ARHX0Bo" crossorigin="anonymous"></script>
      <script>
         // Example starter JavaScript for disabling form submissions if there are invalid fields
         (function () {
           'use strict'
         
           // Fetch all the forms we want to apply custom Bootstrap validation styles to
           var forms = document.querySelectorAll('.needs-validation')
         
           // Loop over them and prevent submission
           Array.prototype.slice.call(forms)
             .forEach(function (form) {
               form.addEventListener('submit', function (event) {
                 if (!form.checkValidity()) {
                   event.preventDefault()
                   event.stopPropagation()
                 }
         
                 form.classList.add('was-validated')
               }, false)
             })
         })()
         
         document.body.addEventListener('htmx:configRequest', (event) => {
           event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
         })
         
         
         
         htmx.on("showSuccessMessage", (e) => {
         toastr.success(e.detail.value, 'Action successfull');
         })
         
         htmx.on("showErrorMessage", (e) => {
         toastr.error(e.detail.value, 'An error occured');
         })
         
         function preventDoubleSubmit(form) {
         form.submit.disabled = true;
         form.submit.value = "Please wait...";
         return true;
         }
         
      </script>
      {% block sitejs %}
      {% endblock sitejs %}
   </body>
</html>

templates/incomes/income-chart.html
<div class="m-b-5">
    <button class="btn btn-outline-primary border-0" hx-trigger="click"  hx-get="{% url 'incomes-table' %}" hx-target="#incomes-card" hx-swap="innerHTML" hx-indicator=".progress-idc">Incomes table</button>
    <button class="btn btn-primary" hx-trigger="click"  hx-get="{% url 'income-chart' %}" hx-target="#incomes-card" hx-swap="innerHTML" hx-indicator=".progress-idc">Incomes chart</button>
</div>
<div class="card h-100">
    <div class="card-body">
       <div id="myPlot"></div>
    </div>
</div>
<script>
    var xArray = [];
    var yArray = {{y_values}};
    
    for(i=40; i<=100; i++)
    {
        xArray.push(i)
    }
    
    // Define Data
    var data = [{
        x:xArray,
        y:yArray,
        type: 'scatter'
    }];
    
    // Define Layout
    var layout = {
        xaxis: { title: "Age", rangemode: "nonnegative"},
        yaxis: { title: "Income", rangemode: "nonnegative"},  
        title: "{{title|default:'Total Income'}}"
    };
    
    // Display using Plotly
    Plotly.newPlot("myPlot", data, layout);
</script>

templates/incomes/income-form.html
{% load widget_tweaks %}
{% with WIDGET_ERROR_CLASS='is-invalid' %}
<div class="card">
    <form id="income-form" class="modal-content" hx-post="{{ request.path }}" onsubmit="return preventDoubleSubmit(this);">
       {% csrf_token %}
       <div class="modal-header">
         <h5 class="modal-title">Add new income</h5>
         <button type="button" class="close" data-dismiss="modal" aria-label="Close">
         <span aria-hidden="true">&times;</span>
         </button>
       </div>
       <div class="card-body">
          <div class="form-group row">
             <label for="id_employee" class="col-sm-8 text-right control-label col-form-label">Income Description</label>
             <div class="col-sm-4">
                {% render_field form.description class="form-control" %}
                <div class="invalid-feedback">{{ form.description.errors|first }}</div>
             </div>
          </div>

          <div class="form-group row">
            <label for="id_annual_amount" class="col-sm-8 text-right control-label col-form-label">Annual amount (such as salary)</label>
            <div class="col-sm-4">
               <div class="input-group">
                  <div class="input-group-prepend">
                      <span class="input-group-text">$</span>
                  </div>
                  {% render_field form.annual_amount class="form-control"  min="0" oninput="this.value = !!this.value && Math.abs(this.value) >= 0 ? Math.abs(this.value) : null"%}
               </div>
               <div class="invalid-feedback">{{ form.annual_amount.errors|first }}</div>
            </div>
         </div>

         <div class="form-group row">
            <label for="id_start_age" class="col-sm-8 text-right control-label col-form-label">When does your income begin (enter an age)</label>
            <div class="col-sm-4">
               {% render_field form.start_age class="form-control" onkeypress="return (event.charCode == 8 || event.charCode == 0 || event.charCode == 13) ? null : event.charCode >= 48 && event.charCode <= 57" %}
               <div class="invalid-feedback">{{ form.start_age.errors|first }}</div>
            </div>
         </div>

         <div class="form-group row">
            <label for="id_end_age" class="col-sm-8 text-right control-label col-form-label">When does your income end (enter an age) </label>
            <div class="col-sm-4">
               {% render_field form.end_age class="form-control" onkeypress="return (event.charCode == 8 || event.charCode == 0 || event.charCode == 13) ? null : event.charCode >= 48 && event.charCode <= 57"%}
               <div class="invalid-feedback">{{ form.end_age.errors|first }}</div>
            </div>
         </div>

         <div class="form-group row">
            <label for="id_growth" class="col-sm-8 text-right control-label col-form-label">Does this income grow over time? If so, how high (in $) will this be when you're 65</label>
            <div class="col-sm-4">
               <div class="input-group">
                  <div class="input-group-prepend">
                      <span class="input-group-text">$</span>
                  </div>
                  {% render_field form.growth class="form-control"  min="0" oninput="this.value = !!this.value && Math.abs(this.value) >= 0 ? Math.abs(this.value) : null"%}
                  <div class="invalid-feedback">{{ form.growth.errors|first }}</div>
               </div>
            </div>
            
         </div>
         
         <input type="submit" name="submit" class="btn btn-primary float-right" value="{% if 'add' in request.path %} Add {% else %} Update {% endif %} Income">
        </div>
    </form>
</div>
{% endwith %}

<script>

</script>
 

templates/incomes/incomes-table.html
{% load static %}
<div hx-trigger="incomesListChanged from:body" hx-get="{% url 'incomes-table' %}" hx-target="#incomes-card">
   {% if incomes %}
   <div class="m-b-5">
      <button class="btn btn-primary" hx-trigger="click"  hx-get="{% url 'incomes-table' %}" hx-target="#incomes-card" hx-swap="innerHTML" hx-indicator=".progress-idc">Incomes table</button>
      {% if incomes|length > 1 %}<button class="btn btn-outline-primary border-0" hx-trigger="click"  hx-get="{% url 'income-chart' %}" hx-target="#incomes-card" hx-swap="innerHTML" hx-indicator=".progress-idc">Incomes chart</button>{% endif %}
   </div>
   <div id="incomes_table" >
      <div class="table-responsive">
         <table id="zero_config" class="table table-striped table-bordered">
            <thead>
               <tr>
                  <th>Description</th>
                  <th>($) Annual amount</th>
                  <th>Start age</th>
                  <th>End age</th>
                  <th>($) Growth</th>
                  <th>Actions</th>
               </tr>
            </thead>
            <tbody>
               {% for income in incomes %}
               <tr>
                  <td>
                     <a href="" hx-trigger="click" hx-get="{% url 'income-chart' %}?pk={{income.id}}&title={{income.description}}" hx-target="#incomes-card" hx-swap="innerHTML" hx-indicator=".progress-idc">
                     {{income.description}}
                     </a>
                  </td>
                  <td>{{income.annual_amount}}</td>
                  <td>{{income.start_age|default:""}}</td>
                  <td>{{income.end_age|default:""}}</td>
                  <td>{{income.growth|default:""}}</td>
                  <td>
                     <i class="fas fa-edit" style="color:#3cd63a; cursor: pointer; padding-right: 5px;" title="Update Income" hx-get="{% url 'update-income' income.id %}" hx-target="#income-form-dialog"></i>
                     <i class="fas fa-trash" style="color:red; cursor: pointer;" title="Delete Income" hx-delete="{% url 'delete-income' income.id %}" hx-confirm="Are you sure you want to delete this income?"></i>
                  </td>
               </tr>
               {% endfor %}
            </tbody>
            <tfoot>
               <tr>
                  <th>Description</th>
                  <th>($) Annual amount</th>
                  <th>Start age</th>
                  <th>End age</th>
                  <th>($) Growth</th>
                  <th>Actions</th>
               </tr>
            </tfoot>
         </table>
      </div>
   </div>
   {% else %}
   <h4> Your incomes list is empty. Try adding some</h4>
   {% endif %}
</div>
{% block sitejs %}
<script>
   $('#zero_config').DataTable(     
      {
          "ordering":false,
      }    
   );
</script>
{% endblock sitejs %}

templates/incomes/incomes.html
{% extends 'base.html' %}
{% load static %}
{% block sitecss %}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<style>
   th{
   background: #e1e4e8;
   }
   tr:hover{
   background: #e1e4e8;
   }
   .break {
   white-space: nowrap;
   }
   .word-wrap{
   overflow-wrap: break-word;
   }
   th{
   background: #e1e4e8;
   }
   tr:hover{
   background: #e1e4e8;
   }
</style>
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/progress-indicator.css' %}">
{% endblock sitecss %}
{% block title %} Kashkoo{% endblock title %}
{% block page_name %} 
{% endblock page_name %}
{% block content %}
<!-- Add income button -->
<div class="modal-btn">
   <button type="button" class="btn btn-primary" hx-get="{% url 'add-income' %}" hx-target="#income-form-dialog" style="border-radius:20px;">
   <i class="fas fa-user-plus"></i> Add Income
   </button>
   <br><br>
</div>
<!-- Add income Modal -->
<div class="modal fade come-from-modal right" id="incomeFormPopup" tabindex="-1" aria-labelledby="incomeFormModalLabel" aria-hidden="true">
   <div id="income-form-dialog" class="modal-dialog mr-0" hx-target="this">
   </div>
</div>
<div class="card">
   <div class="card-body">
      <div class="progress-idc">
         <div class="indeterminate"></div>
      </div>
      <div id="incomes-card" hx-trigger="load from:body" hx-get="{% url 'incomes-table' %}" hx-target="this">
      </div>
   </div>
</div>
{% endblock content %}
{% block sitejs %}
<script src="{% static 'dashboard/js/datatable-checkbox-init.js' %}"></script>
<script src="{% static 'dashboard/js/jquery.multicheck.js' %}"></script>
<script src="{% static 'dashboard/js/datatables.min.js' %}"></script>
<script>
   const add_income_modal = new bootstrap.Modal(document.getElementById("incomeFormPopup"))
   
   
   htmx.on("htmx:afterSwap", (e) => {
       // Response targeting #dialog => show the modal
       if (e.detail.target.id == "income-form-dialog") {
       add_income_modal.show();
       
       }
        
   })
   
   htmx.on("htmx:beforeSwap", (e) => {
       // Empty response targeting #dialog => hide the modal
   
       if (e.detail.target.id == "income-form-dialog" && !e.detail.xhr.response) {
       add_income_modal.hide()
       e.detail.shouldSwap = false
       }
       
   })
   
   htmx.on("hidden.bs.modal", () => {
       document.getElementById("income-form-dialog").innerHTML = "";
   })
</script>
{% endblock sitejs %}

templates/partials/messages.html
{% if messages %}
    {% for message in messages %}
        <script type="text/javascript">toastr.{{ message.tags }}('{{ message }}')</script>
    {% endfor %}
{% endif %}